-- Create a temporary table for usernames
CREATE TEMPORARY TABLE LoginsTemp
(
    UserName NVARCHAR(250)
);


-- Load data from the file into the temporary table
INSERT INTO LoginsTemp (UserName) VALUES
('Alex_Smith'),
('David+Lee'),
('Emma_Watson'),
('Frank.Miller'),
('Grace-Hill'),
('Helen+Clark'),
('Ian_Scott'),
('Julia.Brown'),
('Kevin-White'),
('Laura+Green'),
('Mark_Stevens'),
('Nina.James'),
('Oscar-King'),
('Paula+Young'),
('Quinn_Smith'),
('Rachel.Jones'),
('Steve-Hall'),
('Tina+Moore'),
('Uma_Sharma'),
('Victor.Johnson'),
('Wendy-Kim'),
('Xander+Fox'),
('Yara_Smith'),
('Zane.Jones'),
('Aaron-King'),
('Bella+Stone'),
('Carl_Smith'),
('Diana.Jones'),
('Evan-Hill'),
('Fiona+Clark'),
('Gavin_Scott'),
('Holly.Brown'),
('Ivan-White'),
('Jade+Green'),
('Kyle_Stevens'),
('Lily.James'),
('Mason-King'),
('Nora+Young'),
('Owen_Smith'),
('Penny.Jones'),
('Quincy-Hall'),
('Rita+Moore'),
('Sam_Sharma'),
('Tara.Johnson'),
('Ulysses-Kim'),
('Vera+Fox'),
('Will_Smith'),
('Xena.Jones'),
('Yusuf-King'),
('Zoey+Stone'),
('Amber_Smith'),
('Blake.Jones'),
('Clara-Hill'),
('Derek+Clark'),
('Elena_Scott'),
('Felix.Brown'),
('Gina-White'),
('Harry+Green'),
('Isla_Stevens'),
('Jack.James'),
('Kara-King'),
('Liam+Young'),
('Mia_Smith'),
('Noah.Jones'),
('Olive-Hall'),
('Peter+Moore'),
('Queen_Sharma'),
('Ralph.Johnson'),
('Sophie-Kim'),
('Tom+Fox'),
('Una_Smith'),
('Vince.Jones'),
('Willa-King'),
('Ximena+Stone'),
('Yosef_Smith'),
('Zara.Jones'),
('Aiden-Hill'),
('Brooke+Clark'),
('Chase_Scott'),
('Daisy.Brown'),
('Eli-White'),
('Faith+Green'),
('George_Stevens'),
('Hazel.James'),
('Isaac-King'),
('Jenna+Young'),
('Kurt_Smith'),
('Lana.Jones'),
('Miles-Hall'),
('Nadia+Moore'),
('Omar_Sharma'),
('Piper.Johnson'),
('Quentin-Kim'),
('Rosa+Fox'),
('Sean_Smith'),
('Tessa.Jones');
    
-- Insert new usernames into the Logins table that do not already exist
INSERT INTO Logins (UserName)
SELECT lt.UserName
FROM LoginsTemp lt
LEFT JOIN Logins l ON lt.UserName = l.UserName
where l.UserName IS NULL;
